### ISSUE TITLE
Can't render rabl templates due to frozen opts passed as locals

### ISSUE THREAD

**Issue by badosu** [jeremyevans/roda#115]
The Rabl engine for Tilt changes the locals hash state when rendering (see https://github.com/nesquena/rabl/blob/master/lib/rabl/engine.rb#L405).

The render plugin however provides the `OPTS` hash as locals when none is provided, but this hash is frozen, which gives a `RuntimeError` when it gets to the the aforementioned line. (See https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/render.rb#L149 and https://github.com/jeremyevans/roda/blob/5c142e99c4ad0998a7f7b7b7c669a965ca7aaa65/lib/roda/plugins/render.rb#L255).

The workaround is to explicitly pass `locals: {}` when calling render.

The cause of this error is somewhat evident, but if necessary, I can provide an app with the minimal reproduction.

Backtrace:
<details>
```
RuntimeError - can't modify frozen Hash:
  rabl (0.13.1) lib/rabl/engine.rb:405:in `set_locals'
  rabl (0.13.1) lib/rabl/engine.rb:401:in `set_instance_variables!'
  rabl (0.13.1) lib/rabl/engine.rb:30:in `apply'
  rabl (0.13.1) lib/rabl/template.rb:15:in `evaluate'
  tilt (2.0.7) lib/tilt/template.rb:109:in `render'
  roda (2.25.0) lib/roda/plugins/render.rb:265:in `render'
  lib/mastodon/api.rb:31:in `block (3 levels) in <class:API>'
  roda (2.25.0) lib/roda.rb:767:in `always'
  roda (2.25.0) lib/roda.rb:758:in `_verb'
  roda (2.25.0) lib/roda.rb:388:in `get'
  lib/mastodon/api.rb:20:in `block (2 levels) in <class:API>'
  roda (2.25.0) lib/roda.rb:832:in `if_match'
  roda (2.25.0) lib/roda.rb:464:in `is'
  lib/mastodon/api.rb:19:in `block in <class:API>'
  roda (2.25.0) lib/roda.rb:261:in `block in call'
  roda (2.25.0) lib/roda.rb:259:in `call'
  roda (2.25.0) lib/roda.rb:228:in `block in build_rack_app'
  warden (1.2.7) lib/warden/manager.rb:32:in `call'
  roda (2.25.0) lib/roda.rb:117:in `call'
  actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
  actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
  actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
  bullet (5.5.1) lib/bullet/rack.rb:12:in `call'
  http_accept_language (2.1.0) lib/http_accept_language/middleware.rb:14:in `call'
  rack (2.0.1) lib/rack/deflater.rb:35:in `call'
  rack-attack (5.0.1) lib/rack/attack.rb:147:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:100:in `call'
  activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
  railties (5.0.2) lib/rails/engine.rb:522:in `call'
  puma (3.8.2) lib/puma/configuration.rb:224:in `call'
  puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
  puma (3.8.2) lib/puma/server.rb:435:in `process_client'
  puma (3.8.2) lib/puma/server.rb:299:in `block in run'
  puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
</details>

**Comment by jeremyevans** [comment]
I consider that a bug in the rabl template engine, it shouldn't attempt to mutate its arguments, please submit a bug report to the rabl project.
