### ISSUE TITLE
Unable to test releases

### ISSUE THREAD

**Issue by assistcontrol** [jeremyevans/roda#139]
Am I missing a step for running the specs? After unpacking the roda gem, when I run `rake spec` I get this (first 3 of 14 shown):

```
  1) Error:
static plugin#test_0001_adds support for serving static files:
Errno::ENOENT: No such file or directory @ rb_sysopen - spec/views/about/_test.erb
    /wrkdirs/usr/ports/www/rubygem-roda/work/roda-3.4.0/spec/plugin/static_spec.rb:14:in `read'
    /wrkdirs/usr/ports/www/rubygem-roda/work/roda-3.4.0/spec/plugin/static_spec.rb:14:in `block (2 levels) in <top (required)>'

  2) Error:
static plugin#test_0002_respects the application's :root option:
Errno::ENOENT: No such file or directory @ rb_sysopen - spec/views/about/_test.erb
    /wrkdirs/usr/ports/www/rubygem-roda/work/roda-3.4.0/spec/plugin/static_spec.rb:28:in `read'
    /wrkdirs/usr/ports/www/rubygem-roda/work/roda-3.4.0/spec/plugin/static_spec.rb:28:in `block (2 levels) in <top (required)>'

  3) Error:
timestamp_public plugin#test_0001_adds r.timestamp_public for serving static files from timestamp_public folder:
Errno::ENOENT: No such file or directory @ rb_sysopen - spec/views/about/_test.erb
    /wrkdirs/usr/ports/www/rubygem-roda/work/roda-3.4.0/spec/plugin/timestamp_public_spec.rb:17:in `read'
    /wrkdirs/usr/ports/www/rubygem-roda/work/roda-3.4.0/spec/plugin/timestamp_public_spec.rb:17:in `block (2 levels) in <top (required)>'
```

**Comment by jeremyevans** [comment]
Thanks for reporting this. It looks like the gem doesn't include all files needed for specs, which is a bug.  I'll modify the gemspec to make sure it includes all necessary files, so this will work in the next release.

**Comment by assistcontrol** [comment]
Thanks, Jeremy!
